# Generated by Django 4.1.4 on 2023-01-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Latrello', '0003_alter_card_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'In Progress'), (3, 'In QA'), (4, 'Ready'), (5, 'Done')], default='New'),
        ),
    ]
