# Generated by Django 4.1.4 on 2023-01-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Latrello', '0004_alter_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'In Progress'), (3, 'In QA'), (4, 'Ready'), (5, 'Done')], default=1),
        ),
    ]
